laravel/app/Http/routes.php
<?php

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('historico', 'HistoricoController@index')->name('historico');
    Route::get('clientes', 'ClientesController@index')->name('clientes');
    Route::get('midia', 'MidiaController@index')->name('midia');
    Route::get('midia/{midia_id}', 'MidiaController@show')->name('midia.show');
    Route::get('perfil/{perfil_slug}', 'PerfilController@index')->name('perfil');
    Route::get('plano/{plano_slug}', 'PlanoController@index')->name('plano');
    Route::get('experimente', 'ExperimenteController@index')->name('experimente');
    Route::post('experimente', 'ExperimenteController@post')->name('experimente.post');
    Route::get('imovel', 'ImovelController@index')->name('imovel');
    Route::post('imovel', 'ImovelController@post')->name('imovel.post');
    Route::post('indique', 'IndiqueController@post')->name('indique.post');
    Route::post('contato', 'ContatoController@post')->name('contato.post');
    Route::post('contato-plano', 'ContatoController@postPlano')->name('contato.postPlano');
    Route::get('contato/obrigado', function() {
        return view('frontend.obrigado.contato');
    });
    Route::get('contato-plano/obrigado', function() {
        return view('frontend.obrigado.contato-plano');
    });
    Route::get('indique/obrigado', function() {
        return view('frontend.obrigado.indique');
    });
    Route::get('experimente/obrigado', function() {
        return view('frontend.obrigado.experimente');
    });
    Route::get('imovel/obrigado', function() {
        return view('frontend.obrigado.imovel');
    });

    // Localização
    Route::get('lang/{idioma?}', function ($idioma = 'pt') {
        if (in_array($idioma, ['pt', 'en', 'es'])) {
            Session::put('locale', $idioma);
        }
        return redirect()->route('home');
    })->name('lang');

    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth']
    ], function() {
        Route::get('/', 'PainelController@index')->name('painel');

        /* GENERATED ROUTES */
        Route::get('midia/delete-image/{midia_id}', 'MidiaController@deleteImage')->name('painel.midia.deleteImage');
        Route::get('midia/delete-pdf/{midia_id}', 'MidiaController@deletePdf')->name('painel.midia.deletePdf');
		Route::resource('midia', 'MidiaController');
        Route::get('midia/{midia}/imagens/clear', [
            'as'   => 'painel.midia.imagens.clear',
            'uses' => 'MidiaImagensController@clear'
        ]);
        Route::resource('midia.imagens', 'MidiaImagensController');
		Route::resource('video', 'VideoController', ['only' => ['index', 'update']]);
		Route::resource('historico', 'HistoricoController', ['only' => ['index', 'update']]);
		Route::resource('facilities', 'FacilitiesController', ['only' => ['index', 'update']]);
		Route::resource('comparativo', 'ComparativoController');
        Route::resource('clientes', 'ClientesController');
		Route::resource('perfis', 'PerfisController');
		Route::resource('planos', 'PlanosController');
		Route::resource('solicitacoes-de-test-drive', 'SolicitacoesDeTestDriveController');
		Route::resource('indicacoes', 'IndicacoesController');
		Route::resource('servicos', 'ServicosController');
        Route::resource('contato/recebidos', 'ContatosRecebidosController');
        Route::resource('contato', 'ContatoController');
        Route::resource('imoveis', 'ImoveisRecebidosController');
        Route::resource('usuarios', 'UsuariosController');

        /* FOTOS */
        Route::get('fotos/galeria/{galeria}', 'FotosController@index')->name('painel.fotos.index');
        Route::get('fotos/{fotos}', 'FotosController@show')->name('painel.fotos.show');
        Route::post('fotos/{galeria}', 'FotosController@store')->name('painel.fotos.store');
        Route::patch('fotos/{fotos}', 'FotosController@update')->name('painel.fotos.update');
        Route::delete('fotos/{fotos}', 'FotosController@destroy')->name('painel.fotos.destroy');

        Route::post('order', 'PainelController@order');
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
    });

    // Auth
    Route::group([
        'prefix'    => 'painel',
        'namespace' => 'Auth'
    ], function() {
        Route::get('login', 'AuthController@showLoginForm')->name('auth');
        Route::post('login', 'AuthController@login')->name('login');
        Route::get('logout', 'AuthController@logout')->name('logout');
    });
});

laravel/app/Http/Controllers/Painel/ClientesController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ClientesRequest;
use App\Http\Controllers\Controller;

use App\Models\Cliente;
use App\Helpers\CropImage;

class ClientesController extends Controller
{
    private $image_config = [
        'width'   => 185,
        'height'  => 120,
        'cliente' => true,
        'path'    => 'assets/img/clientes/'
    ];

    public function index()
    {
        $imagens = Cliente::ordenados()->get();

        return view('painel.clientes.index', compact('imagens'));
    }

    public function show(Cliente $imagem)
    {
        return $imagem;
    }

    public function store(ClientesRequest $request)
    {
        try {

            $input = $request->all();
            $input['imagem'] = CropImage::make('imagem', $this->image_config);

            $imagem = Cliente::create($input);

            $view = view('painel.clientes.imagem', compact('imagem'))->render();

            return response()->json(['body' => $view]);

        } catch (\Exception $e) {

            return 'Erro ao adicionar imagem: '.$e->getMessage();

        }
    }

    public function destroy(Cliente $imagem)
    {
        try {

            $imagem->delete();
            return redirect()->route('painel.clientes.index')
                             ->with('success', 'Imagem excluída com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir imagem: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/ComparativoController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ComparativoRequest;
use App\Http\Controllers\Controller;

use App\Models\Comparativo;
use App\Models\Plano;

class ComparativoController extends Controller
{
    public function index()
    {
        $registros = Comparativo::ordenados()->get();

        return view('painel.comparativo.index', compact('registros'));
    }

    public function create()
    {
        $planos = Plano::where('tipo', 1)->orderBy('id', 'ASC')->get();

        return view('painel.comparativo.create', compact('planos'));
    }

    public function store(ComparativoRequest $request)
    {
        try {

            $input  = $request->except('planos');
            $planos = ($request->get('planos') ?: []);

            $registro = Comparativo::create($input);
            $registro->planos()->sync($planos);

            return redirect()->route('painel.comparativo.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Comparativo $registro)
    {
        $planos = Plano::where('tipo', 1)->orderBy('id', 'ASC')->get();

        return view('painel.comparativo.edit', compact('registro', 'planos'));
    }

    public function update(ComparativoRequest $request, Comparativo $registro)
    {
        try {

            $input = $request->except('planos');
            $planos = ($request->get('planos') ?: []);

            $registro->update($input);
            $registro->planos()->sync($planos);

            return redirect()->route('painel.comparativo.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Comparativo $registro)
    {
        try {

            $registro->planos()->detach();
            $registro->delete();
            return redirect()->route('painel.comparativo.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/Painel/ContatoController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ContatoRequest;
use App\Http\Controllers\Controller;

use App\Models\Contato;

class ContatoController extends Controller
{
    public function index()
    {
        $contato = Contato::first();

        return view('painel.contato.index', compact('contato'));
    }

    public function update(ContatoRequest $request, Contato $contato)
    {
        try {

            $input = $request->all();

            $contato->update($input);
            return redirect()->route('painel.contato.index')->with('success', 'Informações alteradas com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar informações: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/ContatosRecebidosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Models\ContatoRecebido;

class ContatosRecebidosController extends Controller
{
    public function index()
    {
        $contatosrecebidos = ContatoRecebido::orderBy('id', 'DESC')->paginate(15);

        return view('painel.contato.recebidos.index', compact('contatosrecebidos'));
    }

    public function show(ContatoRecebido $contato)
    {
        $contato->update(['lido' => 1]);

        return view('painel.contato.recebidos.show', compact('contato'));
    }

    public function destroy(ContatoRecebido $contato)
    {
        try {

            $contato->delete();
            return redirect()->route('painel.contato.recebidos.index')->with('success', 'Mensagem excluída com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir mensagem: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/FacilitiesController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\FacilitiesRequest;
use App\Http\Controllers\Controller;

use App\Models\Facilities;

class FacilitiesController extends Controller
{
    public function index()
    {
        $registro = Facilities::first();

        return view('painel.facilities.edit', compact('registro'));
    }

    public function update(FacilitiesRequest $request, Facilities $registro)
    {
        try {
            $input = $request->all();

            $registro->update($input);

            return redirect()->route('painel.facilities.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/FotosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\FotosRequest;
use App\Http\Controllers\Controller;

use App\Models\Foto;

use App\Helpers\CropImage;

class FotosController extends Controller
{
    private $image_config = [
        [
            'width'  => 268,
            'height' => 178,
            'path'   => 'assets/img/fotos/thumbs/'
        ],
        [
            'width'  => 980,
            'height' => null,
            'upsize' => true,
            'path'   => 'assets/img/fotos/'
        ]
    ];

    private $galerias = [
        'conceito'    => 8,
        'experimente' => 9,
        'contato'     => 5
    ];

    public function index($galeria = null)
    {
        if ( ! array_key_exists($galeria, $this->galerias)) return abort('404');

        $limite = $this->galerias[$galeria];
        $hideCreateBtn = Foto::where('galeria', $galeria)->count() >= $limite;

        $imagens = Foto::where('galeria', $galeria)->ordenados()->get();

        return view('painel.fotos.index', compact('imagens', 'galeria', 'hideCreateBtn', 'limite'));
    }

    public function show(Foto $imagem)
    {
        return $imagem;
    }

    public function store($galeria = null, FotosRequest $request)
    {
        if ( ! array_key_exists($galeria, $this->galerias)) return abort('404');

        $limite = $this->galerias[$galeria];

        if ($limite && Foto::where('galeria', $galeria)->count() >= $limite) {
            return 'Essa galeria já atingiu o limite máximo de fotos.';
        }

        try {

            $input = $request->all();
            $input['imagem'] = CropImage::make('imagem', $this->image_config);

            $imagem = Foto::create($input);

            $imagem->galeria = $galeria;
            $imagem->save();

            $view = view('painel.fotos.imagem', compact('imagem'))->render();

            return response()->json(['body' => $view]);

        } catch (\Exception $e) {

            return 'Erro ao adicionar foto: '.$e->getMessage();

        }
    }

    public function update(FotosRequest $request, Foto $imagem)
    {
        try {

            $imagem->update(['legenda' => $request->get('legenda')]);

            return response()->json(['success' => 'Legenda alterada com sucesso']);

        } catch (\Exception $e) {

            return 'Erro ao alterar legenda: '.$e->getMessage();

        }
    }

    public function destroy(Foto $imagem)
    {
        try {

            $imagem->delete();
            return back()->with('success', 'Foto excluída com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir foto: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/HistoricoController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\HistoricoRequest;
use App\Http\Controllers\Controller;

use App\Models\Historico;

class HistoricoController extends Controller
{
    public function index()
    {
        $registro = Historico::first();

        return view('painel.historico.edit', compact('registro'));
    }

    public function update(HistoricoRequest $request, Historico $registro)
    {
        try {
            $input = $request->all();

            $registro->update($input);

            return redirect()->route('painel.historico.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/ImoveisRecebidosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Models\ImovelRecebido;

class ImoveisRecebidosController extends Controller
{
    public function index()
    {
        $contatosrecebidos = ImovelRecebido::orderBy('id', 'DESC')->paginate(15);

        return view('painel.imoveis.index', compact('contatosrecebidos'));
    }

    public function show(ImovelRecebido $contato)
    {
        $contato->update(['lido' => 1]);

        return view('painel.imoveis.show', compact('contato'));
    }

    public function destroy(ImovelRecebido $contato)
    {
        try {

            $contato->delete();
            return redirect()->route('painel.imoveis.index')->with('success', 'Mensagem excluída com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir mensagem: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/IndicacoesController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\IndicacoesRequest;
use App\Http\Controllers\Controller;

use App\Models\Indicacao;

class IndicacoesController extends Controller
{
    public function index()
    {
        $registros = Indicacao::orderBy('id', 'DESC')->paginate(20);

        return view('painel.indicacoes.index', compact('registros'));
    }
}

laravel/app/Http/Controllers/Painel/PainelController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use DB;

class PainelController extends Controller
{

    public function index()
    {
        return view('painel.home');
    }

    public function order(Request $request)
    {
        if (!$request->ajax()) return false;

        $data  = $request->input('data');
        $table = $request->input('table');

        for ($i = 0; $i < count($data); $i++) {
            DB::table($table)->where('id', $data[$i])->update(array('ordem' => $i));
        }

        return json_encode($data);
    }

}

laravel/resources/views/painel/common/flash.blade.php
@if(session('success'))
   <div class="alert alert-block alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {!! session('success') !!}
    </div>
@endif

@if($errors->any())
    <div class="alert alert-block alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        @foreach($errors->all() as $error)
        {!! $error !!}<br>
        @endforeach
    </div>
@endif

laravel/resources/views/painel/common/nav.blade.php
<ul class="nav navbar-nav">
    <li @if(str_is('painel.video*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.video.index') }}">Vídeo</a>
    </li>
    <li @if(str_is('painel.facilities*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.facilities.index') }}">Facilities</a>
    </li>
    <li @if(str_is('painel.perfis*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.perfis.index') }}">Perfis</a>
    </li>
    <li @if(str_is('painel.planos*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.planos.index') }}">Planos</a>
    </li>
    <li @if(str_is('painel.comparativo*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.comparativo.index') }}">Comparativo</a>
    </li>
    <li @if(str_is('painel.servicos*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.servicos.index') }}">Serviços</a>
    </li>
    <li @if(str_is('painel.historico*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.historico.index') }}">Histórico</a>
    </li>
    <li @if(str_is('painel.clientes*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.clientes.index') }}">Clientes</a>
    </li>
	<li @if(str_is('painel.midia*', Route::currentRouteName())) class="active" @endif>
		<a href="{{ route('painel.midia.index') }}">Mídia</a>
	</li>
    <li class="dropdown @if(str_is('painel.fotos*', Route::currentRouteName())) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Fotos
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li><a href="{{ route('painel.fotos.index', 'conceito') }}">Conceito</a></li>
            <li><a href="{{ route('painel.fotos.index', 'experimente') }}">Experimente</a></li>
            <li><a href="{{ route('painel.fotos.index', 'contato') }}">Contato</a></li>
        </ul>
    </li>
    <li @if(str_is('painel.solicitacoes-de-test-drive*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.solicitacoes-de-test-drive.index') }}">
            Test-Drive
            @if($solicitacoesNaoLidas >= 1)
            <span class="label label-success" style="margin-left:3px;">{{ $solicitacoesNaoLidas }}</span>
            @endif
        </a>
    </li>
    <li @if(str_is('painel.indicacoes*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.indicacoes.index') }}">Indicações</a>
    </li>
    <li class="dropdown @if(str_is('painel.contato*', Route::currentRouteName())) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Contato
            @if($contatosNaoLidos >= 1)
            <span class="label label-success" style="margin-left:3px;">{{ $contatosNaoLidos }}</span>
            @endif
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li><a href="{{ route('painel.contato.index') }}">Informações de Contato</a></li>
            <li><a href="{{ route('painel.contato.recebidos.index') }}">
                Contatos Recebidos
                @if($contatosNaoLidos >= 1)
                <span class="label label-success" style="margin-left:3px;">{{ $contatosNaoLidos }}</span>
                @endif
            </a></li>
        </ul>
    </li>
    <li @if(str_is('painel.imoveis*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.imoveis.index') }}">
            Imóveis
            @if($imoveisNaoLidos >= 1)
            <span class="label label-success" style="margin-left:3px;">{{ $imoveisNaoLidos }}</span>
            @endif
        </a>
    </li>
</ul>

laravel/resources/views/painel/common/template.blade.php
<!doctype html>
<html lang="pt-BR">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <base href="{{ url('/') }}">

    <title>{{ config('site.name') }} - Painel Administrativo</title>

    <link rel="stylesheet" href="{{ asset('assets/vendor/bootswatch-dist/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/vendor/jquery-ui/themes/cupertino/jquery-ui.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/vendor/growl/stylesheets/jquery.growl.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/painel/painel.css') }}">
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url('/') }}">Infinity</a>
            </div>

            <div id="navbar" class="navbar-collapse collapse">
                @include('painel.common.nav')

                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown @if(str_is('painel.usuarios*', Route::currentRouteName())) active @endif">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <span class="glyphicon glyphicon-cog small" style="margin-right:3px"></span>
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="{{ route('painel.usuarios.index') }}">Usuários</a></li>
                            <li><a href="{{ route('logout') }}">Logout</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container" style="padding-bottom:30px;">
        @yield('content')
    </div>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="{{ asset("assets/vendor/jquery/dist/jquery.min.js") }}"><\/script>')</script>
    <script src="{{ asset('assets/vendor/bootswatch-dist/js/bootstrap.min.js') }}"></script>
    <script src="{{ asset('assets/vendor/jquery-ui/jquery-ui.min.js') }}"></script>
    <script src="{{ asset('assets/vendor/bootbox.js/bootbox.js') }}"></script>
    <script src="{{ asset('assets/vendor/ckeditor/ckeditor.js') }}"></script>
    <script src="{{ asset('assets/vendor/blueimp-file-upload/js/jquery.fileupload.js') }}"></script>
    <script src="{{ asset('assets/vendor/growl/javascripts/jquery.growl.js') }}"></script>
    <script src="{{ asset('assets/painel/painel.js') }}"></script>
</body>
</html>